apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service 
  namespace: backend
  labels:
    app: product
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product-service
          image: 
          ports:
            - containerPort: 8080
              name: product-backend
          resources:
            requests:
              cpu: 1024m
              memory: 800Mi
            limits:
              cpu: 2048m
              memory: 1200Mi
          livenessProbe:
            tcpSocket:
              port: 8080
            initalDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThshold: 3
          readinressProbe:
            tcpSocket:
              port: 8080
            initalDelaySeconds: 15
            periodSeconds: 10
            successThshold: 2
            failureThshold: 3
