apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: backupend
  labels:
    app: product
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: metrics
  type: ClusterIP
